broadinstitute/terraform-jade

- env_svc.json.ctmpl
- jade-cloudsql-100-vars.tf.ctmpl
- jade-us-central-k8s-vars.tf.ctmpl
- tfstate_svc.json.ctmpl
- variables.tf.ctmpl
If you have an alias in bash please change it to the following command
```$ docker run --rm -it -v "$PWD":/working -v ${HOME}/.vault-token:/root/.vault-token broadinstitute/dsde-toolbox:consul-0.20.0 ./mkEnv.sh```
> updated syntax to consul v0.20.0

- dev.tf.ctmpl
> DR-902: add SH dev IPs

- bq.tf
- bq.tf.ctmpl
Add a BQ view of user requests
> Add all_user_requests BQ view

- .gitignore
- bq.tf.ctmpl
BigQuery views automatically determine the appropriate schema.
> Remove schema for view

- api-services.tf
- bq.tf.ctmpl
- dev.tf.ctmpl
- grafana-sa.tf
- iam.tf
- integration.tf.ctmpl
- jade-cloudsql-db-users.tf
- jade-cloudsql-sa.tf
- logsink.tf
- nat.tf
- network.tf
- variables.tf.ctmpl
- removed monster dev repo as not needed anymore 
- added workload identity bindings for dev/int for sql gsa to ksa
- house keeping replaced var.project for terraform data resource data.google_project.project.name
> Workload Identity and some house cleaning

- dev.tf.ctmpl
- integration.tf.ctmpl
Appears that only 1 google service account can be bound to one kubernetes service account so heres the 1:1 fix
> Workload Identity fix

- .dependabot/config.yml
- environments/alpha/main.tf
- environments/alpha/variables.tf
- environments/perf/main.tf
- environments/staging/main.tf
- environments/staging/variables.tf
- modules/core-infrastructure/kubernetes.tf
- modules/core-infrastructure/variables.tf
Added ability to add argocd ips to kubenetes master auth whitelist so AP argo can control the deploy.
> Ms alphafix

- README.md
> add quickstart README

- environments/alpha/variables.tf
- environments/dev-developer/variables.tf
- environments/ms/variables.tf
- environments/perf/variables.tf
- environments/production/variables.tf
- environments/staging/variables.tf
- old/dev.tf.ctmpl
- old/jade-us-central-k8s-vars.tf.ctmpl
I believe these are the correct bits to set but would love confirmation (and then would love to know the best way to apply these changes)
> Add nm DNS and DB entries

- datarepo/main.tf
- datarepo/tfvars/alpha.tfvars
- datarepo/tfvars/production.tfvars
- datarepo/tfvars/staging.tfvars
- datarepo/variables.tf
- modules/datarepo-app/cloudsql.tf
- modules/datarepo-app/variables.tf
Ensure that datarepo CloudSQL instances can handle spike in load.
> DR-1502: Bump up CloudSQL size and set max connections

- .github/workflows/terraformMergeApply.yml
- datarepo/main.tf
- datarepo/modules/alerts/alerts.tf
- datarepo/modules/alerts/prometheus.tf
- datarepo/modules/alerts/variables.tf
- datarepo/modules/core-infrastructure/dns_zone.tf
- datarepo/modules/core-infrastructure/kubernetes.tf
- datarepo/modules/core-infrastructure/nat.tf
- datarepo/modules/core-infrastructure/network.tf
- datarepo/modules/core-infrastructure/variables.tf
- datarepo/modules/datarepo-app/cloudsql.tf
- datarepo/modules/datarepo-app/dns.tf
- datarepo/modules/datarepo-app/serviceaccounts.tf
- datarepo/modules/datarepo-app/variables.tf
- datarepo/modules/datarepo-app/workloadidentity.tf
- datarepo/modules/multi-tenant/db.tf
- datarepo/modules/multi-tenant/variables.tf
- datarepo/modules/multi-tenant/workloadid.tf
- datarepo/modules/production-monitoring/sinks.tf
- datarepo/modules/production-monitoring/variables.tf
- datarepo/modules/workloadidentity/variables.tf
- datarepo/modules/workloadidentity/workloadid.tf
- datarepo/variables.tf
depends_on new feature: https://www.hashicorp.com/blog/terraform-0-13-brings-powerful-meta-arguments-to-modular-workflows
old crappy hack: https://github.com/hashicorp/terraform/issues/1178
> Removed dependencies hack and added 0.13 syntax depends_on

- datarepo/modules/core-infrastructure/kubernetes.tf
- datarepo/modules/core-infrastructure/network.tf
- datarepo/modules/core-infrastructure/serviceaccount.tf
- datarepo/modules/core-infrastructure/variables.tf
- datarepo/modules/datarepo-app/cloudsql.tf
- datarepo/terraform.tf
This plan should delete the previous node pool
> Dr 1589 CIS Best Practices

- datarepo/main.tf
- datarepo/modules/core-infrastructure/kms.tf
- datarepo/modules/core-infrastructure/kubernetes.tf
- datarepo/modules/core-infrastructure/serviceaccount.tf
- datarepo/modules/core-infrastructure/variables.tf
"Encrypt Kubernetes secrets, stored in etcd, at the application-layer using a customer-managed key in Cloud KMS."
Would like to manually apply to perf to test first.
> added kms for kube secret encryption

- datarepo/modules/alerts/alerts.tf
https://broadinstitute.slack.com/archives/CADU7L0SZ/p1623961613202000
> [DDO-1312] Make the alert slack token sensitive

- datarepo/main.tf
- datarepo/modules/datarepo-app/serviceaccounts.tf
- datarepo/modules/datarepo-app/variables.tf
- datarepo/tfvars/alpha.tfvars
- datarepo/tfvars/perf.tfvars
- datarepo/tfvars/production.tfvars
- datarepo/tfvars/staging.tfvars
- datarepo/variables.tf
- old/iam.tf
Grant the jade dev service account permissions to the folder used by RBS.
> [DR-1891] Add folder roles for data repo SA

- old/dev.tf.ctmpl
Set up resources for new Azure environment in the dev data repo google project. These changes must be applied manually.
> [DR-2231] Add azure dev environment

- datarepo/modules/alerts/alerts.tf
- datarepo/modules/alerts/variables.tf
Make sure that in addition to #jade-alerts, we also notify the #workbench-oncall slack channel when there's a problem
> DR-2275 Make sure we notify the on call channel

- datarepo/modules/core-infrastructure/serviceaccount.tf
- datarepo/modules/datarepo-app/serviceaccounts.tf
- datarepo/modules/datarepo-app/variables.tf
- datarepo/variables.tf
Notes on what was removed / changed can be found here:
https://docs.google.com/document/d/1K3xz1l4NuCkjtoHWOanU28-RfuDrwDTfCaUpFIjD7no/edit#
> DR-2241 Remove all admin roles from service accounts

- .github/workflows/terraformMergeApply.yml
- datarepo/modules/datarepo-app/variables.tf
Drive by: fixing a permission to not use legacy permissions
> DR-2311 make apply runnable in Github

- datarepo/tfvars/production.tfvars
- old/README.md
- old/dev.tf.ctmpl
- https://broadworkbench.atlassian.net/browse/DR-2524
I am following step 8.1 in our ["Jade Getting Started"](https://github.com/DataBiosphere/jade-data-repo/blob/develop/docs/jade-getting-started.md) guide to add my initials to our Terraform templates.
While here, I updated the README for better readability.
I'll note that I haven't yet applied the changes: `./terraform.sh plan` yielded a larger plan than I'd expected, so I've attached it here and would appreciate an explicit thumbs up on it before applying.  Thanks!
[terraform-plan.txt](https://github.com/broadinstitute/terraform-jade/files/8412948/terraform-plan.txt)
> [DR-2524] Add Olivia's initials to Terraform templates

- datarepo/modules/core-infrastructure/os_login.tf
- datarepo/modules/core-infrastructure/variables.tf
This reverts commit 34625824f5e8b6a0c0da9696e23400f52b1aeb22, reversing changes made to bb97a47de326d0ecd85348a6d43703a19d1c591d.
> Don't Terraform oslogin option because custom roles can't apply it

- README.md
- old/README.md
- old/bq.tf.ctmpl
- old/dev.tf.ctmpl
- old/iam.tf
- old/logsink.tf
- old/provider.tf
- old/terraform.sh
- old/variables.tf.ctmpl
This PR updates some broken things in the `/old/` (e.g. dev) Terraform defs.
I broke these down commit by commit so feel free to go these commit at a time to see the changes (they're not huge)
Changes are all already applied.
I'll do a followup to remove some of the older dev resources
> DR-2755 Fixes to dev terraform
